version: '3'

services:

  # App backend service
  cars-server:
    build:
      context: ../DHV-cars-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - cars-db-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cars-db-mysql:3306/cars?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: quanpan302
      SPRING_DATASOURCE_PASSWORD: quanpan302
    networks:
      - backend
      - frontend

  # Frontend Service
  cars-client:
    build:
      context: ../DHV-cars-client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - cars-server
    networks:
      - frontend

  # Database Service (Mysql)
  cars-db-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: cars
      MYSQL_USER: quanpan302
      MYSQL_PASSWORD: quanpan302
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - cars-db-mysql-data:/var/lib/mysql
    networks:
      - backend

# Volumes
volumes:
  cars-db-mysql-data:

# Networks
networks:
  backend:
  frontend:    
