apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-server
  labels:
    app: cars-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars-server
  template:
    metadata:
      labels:
        app: cars-server
    spec:
      containers:
        - name: cars-server
          image: qpanprojects/demo:cars-server
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-user-pass
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                name: mysql-user-pass
                key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-db-url
                  key: url
---
apiVersion: v1
kind: Service
metadata:
  name: cars-server
  labels:
    app: cars-server
spec:
  type: NodePort
  selector:
    app: cars-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
