apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars-client
  template:
    metadata:
      labels:
        app: cars-client
    spec:
      containers:
        - name: cars-client
          image: qpanprojects/demo:cars-client
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 0.2
              memory: "10Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: cars-client
spec:
  type: NodePort
  selector:
    app: cars-client
  ports:
    - name: http
      port: 80
      targetPort: 80